### ISSUE TITLE
ArchiveManager swollows file extension

### ISSUE THREAD

**Issue by con-f-use** [krzysztofzuraw/blog-projects#1]
Just because I enjoy necroposting, here is a "very important" issue:

https://github.com/krzysztofzuraw/blog-projects/blob/eedb115b3b8033a943433935fc6e7bb9d7a85fa6/factory_pattern/factory.py#L43

should be something like:
```
        self.location_path = location_path
        _, self.extension = os.path.splitext(location_path)
```

**Comment by krzysztofzuraw** [comment]
Hello, thanks for an issue! I will look into it in following days.

**Comment by krzysztofzuraw** [comment]
Fixed thank you: https://krzysztofzuraw.com/blog/2016/factory-pattern-python.html 👍
